async function submitRegistration() {
  const email = document.getElementById("email-input").value;
  const firstname = document.getElementById("firstname-input").value;
  const lastname = document.getElementById("lastname-input").value;
  const errorElement = document.getElementById("error-message");
  const apikey = document.getElementById("apikey-output");

  var body = { email, firstname, lastname };
  console.log(body);
  var response = await fetch("http://localhost:3000/register", {
    method: "post",
    body: JSON.stringify(body),
    headers: { "Content-Type": "application/json" },
  });
  var data = await response.json();
  console.log(data.jwt);

  apikey.innerHTML = data.jwt;
}

// curl -X GET https://api.moesif.com/v1 \
//   -H 'Accept: application/json' \
//   -H 'Authorization:Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhcHAiOiI5Nzk6MTM3Iiwic3ViIjoiZ29vZ2xlLW9hdXRoMnwxMDQ1NDA0MzM1Mzg5NzgyMjU0NDgiLCJhdWQiOiI2dVowbk9qZnJyOE5JajRyOEk2Tk51clN2RjdWWTJtTCIsInZlciI6IjEiLCJvcmciOiIxMDQ3OjkzIiwicGVybWlzc2lvbnMiOnsiMTA0Nzo5MyI6eyJzY3AiOiJjcmVhdGU6YWNjZXNzX3Rva2VucyBjcmVhdGU6ZW5jcnlwdGVkX2tleXMgZGVsZXRlOmVuY3J5cHRlZF9rZXlzIHJlYWQ6ZW5jcnlwdGVkX2tleXMgdXBkYXRlOmVuY3J5cHRlZF9rZXlzIGNyZWF0ZTpldGhfYWJpIGNyZWF0ZTphcHBzIGRlbGV0ZTphcHBzIHJlYWQ6YXBwcyB1cGRhdGU6YXBwcyB1cGRhdGU6b3JnYW5pemF0aW9ucyBjcmVhdGU6Y29ob3J0cyBkZWxldGU6Y29ob3J0cyByZWFkOmNvaG9ydHMgdXBkYXRlOmNvaG9ydHMgY3JlYXRlOnZpcnR1YWxfZXZlbnR0eXBlcyBkZWxldGU6dmlydHVhbF9ldmVudHR5cGVzIHJlYWQ6dmlydHVhbF9ldmVudHR5cGVzIHVwZGF0ZTp2aXJ0dWFsX2V2ZW50dHlwZXMgY3JlYXRlOmNvbXBhbmllcyBkZWxldGU6Y29tcGFuaWVzIHJlYWQ6Y29tcGFuaWVzIHVwZGF0ZTpjb21wYW5pZXMgY3JlYXRlOmV2ZW50cyByZWFkOmV2ZW50cyBjcmVhdGU6cmVwb3J0cyBkZWxldGU6cmVwb3J0cyByZWFkOnJlcG9ydHMgY3JlYXRlOnVzZXJzIGRlbGV0ZTp1c2VycyByZWFkOnVzZXJzIHVwZGF0ZTp1c2VycyBjcmVhdGU6ZGFzaGJvYXJkcyBkZWxldGU6ZGFzaGJvYXJkcyByZWFkOmRhc2hib2FyZHMgdXBkYXRlOmRhc2hib2FyZHMgcmVhZDpwdWJsaWNfd29ya3NwYWNlcyBjcmVhdGU6d29ya3NwYWNlcyBkZWxldGU6d29ya3NwYWNlcyByZWFkOndvcmtzcGFjZXMgdXBkYXRlOndvcmtzcGFjZXMifX0sImlzcyI6Imh0dHBzOi8vd3d3Lm1vZXNpZi5jb20vd3JhcC9hcHAvMTA0Nzo5My05Nzk6MTM3IiwiaWF0IjoxNjY1OTY0ODAwLCJqdGkiOiJlNTViZGM0Mi1jNGI5LTQ1N2MtODA3ZC1lMjQ0NWYyY2M2N2QifQ.oK9QDCyVP6XktDc0Bmr1QK-3s5Sk8GEeGniZ7YFRKuw'

// curl -X POST 'https://api.moesif.com/search/~/count/events?from=-720h&to=now' \
//   -H 'Content-Type: application/json' \
//   -H 'Authorization:Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhcHAiOiI5Nzk6MTM3Iiwic3ViIjoiZ29vZ2xlLW9hdXRoMnwxMDQ1NDA0MzM1Mzg5NzgyMjU0NDgiLCJhdWQiOiI2dVowbk9qZnJyOE5JajRyOEk2Tk51clN2RjdWWTJtTCIsInZlciI6IjEiLCJvcmciOiIxMDQ3OjkzIiwicGVybWlzc2lvbnMiOnsiMTA0Nzo5MyI6eyJzY3AiOiJjcmVhdGU6YWNjZXNzX3Rva2VucyBjcmVhdGU6ZW5jcnlwdGVkX2tleXMgZGVsZXRlOmVuY3J5cHRlZF9rZXlzIHJlYWQ6ZW5jcnlwdGVkX2tleXMgdXBkYXRlOmVuY3J5cHRlZF9rZXlzIGNyZWF0ZTpldGhfYWJpIGNyZWF0ZTphcHBzIGRlbGV0ZTphcHBzIHJlYWQ6YXBwcyB1cGRhdGU6YXBwcyB1cGRhdGU6b3JnYW5pemF0aW9ucyBjcmVhdGU6Y29ob3J0cyBkZWxldGU6Y29ob3J0cyByZWFkOmNvaG9ydHMgdXBkYXRlOmNvaG9ydHMgY3JlYXRlOnZpcnR1YWxfZXZlbnR0eXBlcyBkZWxldGU6dmlydHVhbF9ldmVudHR5cGVzIHJlYWQ6dmlydHVhbF9ldmVudHR5cGVzIHVwZGF0ZTp2aXJ0dWFsX2V2ZW50dHlwZXMgY3JlYXRlOmNvbXBhbmllcyBkZWxldGU6Y29tcGFuaWVzIHJlYWQ6Y29tcGFuaWVzIHVwZGF0ZTpjb21wYW5pZXMgY3JlYXRlOmV2ZW50cyByZWFkOmV2ZW50cyBjcmVhdGU6cmVwb3J0cyBkZWxldGU6cmVwb3J0cyByZWFkOnJlcG9ydHMgY3JlYXRlOnVzZXJzIGRlbGV0ZTp1c2VycyByZWFkOnVzZXJzIHVwZGF0ZTp1c2VycyBjcmVhdGU6ZGFzaGJvYXJkcyBkZWxldGU6ZGFzaGJvYXJkcyByZWFkOmRhc2hib2FyZHMgdXBkYXRlOmRhc2hib2FyZHMgcmVhZDpwdWJsaWNfd29ya3NwYWNlcyBjcmVhdGU6d29ya3NwYWNlcyBkZWxldGU6d29ya3NwYWNlcyByZWFkOndvcmtzcGFjZXMgdXBkYXRlOndvcmtzcGFjZXMifX0sImlzcyI6Imh0dHBzOi8vd3d3Lm1vZXNpZi5jb20vd3JhcC9hcHAvMTA0Nzo5My05Nzk6MTM3IiwiaWF0IjoxNjY1OTY0ODAwLCJqdGkiOiJlNTViZGM0Mi1jNGI5LTQ1N2MtODA3ZC1lMjQ0NWYyY2M2N2QifQ.oK9QDCyVP6XktDc0Bmr1QK-3s5Sk8GEeGniZ7YFRKuw' \
//   -d '{"post_filter":{"bool":{"should":{"term":{"user_id.raw":"eyJhcHAiOiI5Nzk6MTM3IiwidmVyIjoiMi4wIiwib3JnIjoiMTA0Nzo5MyIsImlhdCI6MTY2NDU4MjQwMH0.vzZPW6Mu4VjAVJRnDInenoUlShtGFxOTtHifpVVAuOU"}}}}}'
